[package]
name = "devbox"
version = "1.2.0"
description = "本地开发帮助工具箱"
authors = ["you"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "devbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "~2.12", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
sysinfo = "0.30"
dirs = "5"
tiny_http = "0.12"
ctrlc = { version = "3", features = ["termination"] }
tauri-plugin-notification = "2"

[features]
# 默认无额外特性
default = []
